"""add embedding metadata to connections

Revision ID: f5f051fc9433
Revises: f4e6c1a2b9d0
Create Date: 2026-10-07 23:27:22.665399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5f051fc9433'
down_revision: Union[str, Sequence[str], None] = 'f4e6c1a2b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('connections', sa.Column('embedding_dim', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'embedding_dim')
    op.drop_column('connections', 'embedding_model')
    # ### end Alembic commands ###
