"""Generate the checked-in Stage 4 security corpus report."""

from __future__ import annotations

from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "backend" / "tests" / "security" / "corpus.yaml"
REPORT = ROOT / "docs" / "security.md"


def main() -> None:
    cases = yaml.safe_load(CORPUS.read_text(encoding="utf-8"))
    blocked = [case for case in cases if case["expected"] == "blocked"]
    passed = [case for case in cases if case["expected"] == "pass"]
    kinds: dict[str, int] = {}
    for case in blocked:
        kinds[case["kind"]] = kinds.get(case["kind"], 0) + 1
    rows = "\n".join(f"| `{kind}` | {count} |" for kind, count in sorted(kinds.items()))
    REPORT.write_text(
        f"""# Security Report

Generated by `scripts/generate_security_report.py` from the committed validator corpus.

## Validator corpus

- Cases: {len(cases)}
- Blocked: {len(blocked)}
- Benign statements accepted: {len(passed)}

| Rejection kind | Cases |
| --- | ---: |
{rows}

## Database boundary defense

The integration suite bypasses the validator through the test-only internal value
constructor and proves that PostgreSQL still blocks five representative threats:
write DML, data-modifying CTEs, `SELECT INTO`, `pg_sleep` (statement timeout),
and `pg_read_file` (role privileges). The executor additionally forces every
transaction to read-only mode.

Sensitive-column policy is intentionally **validator-only defense**: the demo
readonly role may select `customers.email`, so metadata policy must prevent that
value from reaching execution. This is covered by a dedicated integration test.
""",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
